name: Passenger generic binaries tests CI tests

env:
  ENTERPRISE: 0

on:
  push:
    branches: [ 'stable-*', 'feature/*' ]
  pull_request:
    branches: [ 'stable-*', 'feature/*' ]

jobs:
  build:
    name: "Binary automation ${{ matrix.os.family }}-${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        os:
          - img: macos-13
            family: macos
          - img: ubuntu-latest
            family: linux
        arch:
          - x86_64
          - aarch64
    runs-on: ${{ matrix.os.img }}${{ matrix.os.family == 'macos' && matris.arch == 'aarch64' && '-arm64' || '' }}
    env:
      WORKSPACE: ${{ github.workspace }}
      OUTPUT_DIR: ${{ github.workspace }}/output-${{ matrix.os.family }}-${{ matrix.arch }}
      ARCHITECTURE: ${{ matrix.arch }}
      CACHE_DIR: ${{ github.workspace }}/cache/${{ matrix.os.family }}-${{ matrix.arch }}/executor-${{ github.run_id }}
      RUNTIME_DIR: ${{ github.workspace }}/cache/${{ matrix.os.family }}-${{ matrix.arch }}/executor-${{ github.run_id }}/runtime
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - run: ./dev/ci/tests/binaries/prepare-macos
      if: matrix.os.family == 'macos'
    - run: ./dev/ci/tests/binaries/build-${{ matrix.os.family }}
    - uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.os.family }}-${{ matrix.arch }}
        path: 'output-${{ matrix.os.family }}-${{ matrix.arch }}/**/*'
    - run: ./dev/ci/tests/binaries/test-${{ matrix.os.family }}
