name: Passenger generic binaries tests CI tests

env:
  ENTERPRISE: 0

on:
  push:
    branches: [ 'stable-*', 'feature/*' ]
  pull_request:
    branches: [ 'stable-*', 'feature/*' ]

jobs:
  build_linux:
    name: "Binary automation Linux-${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
    runs-on: ubuntu-latest
    env:
      WORKSPACE: ${{ github.workspace }}
      OUTPUT_DIR: ${{ github.workspace }}/output-linux-${{ matrix.arch }}
      ARCHITECTURE: ${{ matrix.arch }}
      CACHE_DIR: ${{ github.workspace }}/cache/linux-${{ matrix.arch }}/executor-${{ github.run_id }}
      RUNTIME_DIR: ${{ github.workspace }}/cache/linux-${{ matrix.arch }}/executor-${{ github.run_id }}/runtime
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - run: ./dev/ci/tests/binaries/build-linux
    - uses: actions/upload-artifact@v4
      with:
        name: binaries-linux-${{ matrix.arch }}
        path: 'output-linux-${{ matrix.arch }}/**/*'
    - run: ./dev/ci/tests/binaries/test-linux

  build_macos:
    name: "Binary automation macOS-${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
    runs-on: macos-${{ matrix.arch == 'x86_64' && '13' || 'latest' }}
    env:
      WORKSPACE: ${{ github.workspace }}
      OUTPUT_DIR: ${{ github.workspace }}/output-macos-${{ matrix.arch }}
      ARCHITECTURE: ${{ matrix.arch }}
      CACHE_DIR: ${{ github.workspace }}/cache/macos-${{ matrix.arch }}/executor-${{ github.run_id }}
      RUNTIME_DIR: ${{ github.workspace }}/cache/macos-${{ matrix.arch }}/executor-${{ github.run_id }}/runtime
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: ./dev/ci/tests/binaries/prepare-macos
    - run: ./dev/ci/tests/binaries/build-macos
    - uses: actions/upload-artifact@v4
      with:
        name: binaries-macos-${{ matrix.arch }}
        path: 'output-macos-${{ matrix.arch }}/**/*'
    - run: ./dev/ci/tests/binaries/test-macos
